[build]
publish = "public"
command = "./stackbit-build.sh"

[[redirects]]
  from = "/posts/2019-06-17_using-onesignal-in-a-vue-cli-3-application"
  to = "/posts/using-onesignal-in-a-vue-cli-3-application"
  status = 301